[project]
name = "rag-react-mcp-demo"
version = "0.1.0"
description = "LangGraph agent demos: RAG, ReAct agents with tools, and MCP server integration"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11,<4.0"
dependencies = [
    "langchain>=0.2.14",
    "langchain-community>=0.3.30",
    "langchain-openai>=0.1.22",
    "langchain-tavily>=0.1",
    "langchain-mcp-adapters>=0.1.11",
    "langgraph>=0.6.6,<0.7.0",
    "langgraph-cli[inmem]>=0.4.2",
    "mcp>=1.16.0",
    "fastmcp>=2.12.4",
    "python-dotenv>=1.0.1",
    "pymupdf>=1.26.4",
    "qdrant-client>=1.15.1",
    "tiktoken>=0.12.0",
    "firecrawl>=4.3.6",
    "langchain-qdrant>=0.2.1",
    "ibm-watsonx-gov>=1.3.3",
    "ibm-watsonx-ai>=1.4.11"
]

[tool.setuptools.packages.find]
include = ["studio*"]
